### ISSUE TITLE
Tag Creation Should Create Tags With Rules

### ISSUE THREAD

**Issue by elubow** [elubow/bjjdb#70]
Update tags actions/pages to ensure that start-end positions are linked to the matching position. The following rules apply:
* tags that have a category of `start/end` position can't be edited individually. They always match their counterpart in the `position` category
* when a new `position` tag is created, a corresponding `start-position` and `end-position` tag is created
* you can't create just a `start/end` or just a `position` tag, all 3 need to be there

**Comment by Vexxenn** [comment]
@elubow Regarding the first rule what should happen if we already have the three tags (start, end and position) and we change the category? 
I assume the the first rule would be something of the type
`start-position::in-guard|position::in-guard|end-position::in-guard` 
and then if we changed the name they would all change to the same name 
`start-position::in-guard2|position::in-guard2|end-position::in-guard2`
but what happens if we had something like 
`start-position1::in-guard|position::in-guard|end-position::in-guard`

**Comment by elubow** [comment]
@Vexxenn The categories are somewhat immutable. The idea is that they are a primary means of organization for the links. So I wouldn't be changing the category name at any point.  The rule of `+1000` was my original matching idea. But then I realized I didn't need to actually match them since all the queries are not done by matching ids, but by matching names. So the `+1000` stuff is basically just remnant from a previous idea that I had for how the SQL would function.

**Comment by Vexxenn** [comment]
@elubow Sorry i should have specified what i meant a bit better. What i meant was more along the line of given the situation `start-position1::in-guard|position::in-guard|end-position::in-guard` and i edit the first tag. In the `tags#edit` i can change both the category and the name of the tag, if i change the name i can just update all the tags that had the original name. What happens if change the category of the tag? Since i can change the category i could create a situation where i have the tags `position::in-guard|end-position::in-guard` but lack the tag `start-position1::in-guard` because i changed it's category.
In regards to the rule yea you are right we can use the `Tag.find_by_full_name`.
One final question regarding the last rule. In the case that i try to create a tag with `position X` it should just create the corresponding `start-position` and `end-position` tags (as stated in rule 2). If the admin decided to first create a new tag with the `start-position X`, should it just create the corresponding `position` and `end-position` tags or should i just say he cant do it and must first create a tag with `position X`.

**Comment by elubow** [comment]
@Vexxenn I get what you meant. I will never change the category of the tag. In fact, I would be fine with disabling the category of the tag from being editable altogether. This way, when you change the name, it updates all the names.

No one should have the ability to create only one of them. The easiest way to do it (I think) is that an admin can only create or modify a `position`. Then the start and end positions are automatically created or modified as appropriate.

**Comment by elubow** [comment]
#81

**Comment by elubow** [comment]
@Vexxenn I attempted to add a new `position` called `in-submission` and I think the IDs collide when the actual creation is attempted.

<img width="1595" alt="Screen Shot 2019-04-23 at 11 24 53" src="https://user-images.githubusercontent.com/82815/56570056-828b4b00-65ba-11e9-8fd2-3a3a1950bc0b.png">

**Comment by Vexxenn** [comment]
@elubow Yea since it's trying to force the ID it will fail in the case of there being an existing tag with said ID. Removing the ID +1000 plus ID+2000 and letting the auto-increment do the work should fix it. Will take care of that in a min.

**Comment by elubow** [comment]
PR #85

**Comment by elubow** [comment]
@Vexxenn This works now. Thank you.
